# **OpenAi Models**

In [ ]:
%%capture
!pip install openai==1.55.3 httpx==0.27.2 --force-reinstall --quiet

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
from openai import OpenAI
import os

client = OpenAI(
    # This is the default and can be omitted
    api_key='xxx',
)

models = client.models.list()

print(models)

SyncPage[Model](data=[Model(id='gpt-4.5-preview', created=1740623059, object='model', owned_by='system'), Model(id='gpt-4.5-preview-2025-02-27', created=1740623304, object='model', owned_by='system'), Model(id='gpt-4o-mini-audio-preview-2024-12-17', created=1734115920, object='model', owned_by='system'), Model(id='dall-e-3', created=1698785189, object='model', owned_by='system'), Model(id='dall-e-2', created=1698798177, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview-2024-10-01', created=1727389042, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview', created=1727460443, object='model', owned_by='system'), Model(id='gpt-4o-mini-realtime-preview-2024-12-17', created=1734112601, object='model', owned_by='system'), Model(id='gpt-4o-mini-realtime-preview', created=1734387380, object='model', owned_by='system'), Model(id='o1-mini-2024-09-12', created=1725648979, object='model', owned_by='system'), Model(id='o1-mini', created=1725649008, object='model', owned_by='system'), Model(id='omni-moderation-latest', created=1731689265, object='model', owned_by='system'), Model(id='gpt-4o-mini-audio-preview', created=1734387424, object='model', owned_by='system'), Model(id='omni-moderation-2024-09-26', created=1732734466, object='model', owned_by='system'), Model(id='whisper-1', created=1677532384, object='model', owned_by='openai-internal'), Model(id='gpt-4o-realtime-preview-2024-10-01', created=1727131766, object='model', owned_by='system'), Model(id='babbage-002', created=1692634615, object='model', owned_by='system'), Model(id='gpt-4-turbo-preview', created=1706037777, object='model', owned_by='system'), Model(id='chatgpt-4o-latest', created=1723515131, object='model', owned_by='system'), Model(id='tts-1-hd-1106', created=1699053533, object='model', owned_by='system'), Model(id='text-embedding-3-large', created=1705953180, object='model', owned_by='system'), Model(id='gpt-4-0125-preview', created=1706037612, object='model', owned_by='system'), Model(id='gpt-4o-audio-preview-2024-12-17', created=1734034239, object='model', owned_by='system'), Model(id='gpt-4o-2024-05-13', created=1715368132, object='model', owned_by='system'), Model(id='gpt-4', created=1687882411, object='model', owned_by='openai'), Model(id='gpt-4o-mini-2024-07-18', created=1721172717, object='model', owned_by='system'), Model(id='gpt-4o-mini', created=1721172741, object='model', owned_by='system'), Model(id='tts-1-hd', created=1699046015, object='model', owned_by='system'), Model(id='o1-preview', created=1725648897, object='model', owned_by='system'), Model(id='o1-preview-2024-09-12', created=1725648865, object='model', owned_by='system'), Model(id='gpt-4o-2024-11-20', created=1739331543, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-instruct-0914', created=1694122472, object='model', owned_by='system'), Model(id='tts-1', created=1681940951, object='model', owned_by='openai-internal'), Model(id='tts-1-1106', created=1699053241, object='model', owned_by='system'), Model(id='davinci-002', created=1692634301, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-1106', created=1698959748, object='model', owned_by='system'), Model(id='gpt-4-turbo', created=1712361441, object='model', owned_by='system'), Model(id='o3-mini', created=1737146383, object='model', owned_by='system'), Model(id='o3-mini-2025-01-31', created=1738010200, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-instruct', created=1692901427, object='model', owned_by='system'), Model(id='o1', created=1734375816, object='model', owned_by='system'), Model(id='gpt-4o-2024-08-06', created=1722814719, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-0125', created=1706048358, object='model', owned_by='system'), Model(id='gpt-4o-realtime-preview-2024-12-17', created=1733945430, object='model', owned_by='system'), Model(id='gpt-3.5-turbo', created=1677610602, object='model', owned_by='openai'), Model(id='gpt-4-turbo-2024-04-09', created=1712601677, object='model', owned_by='system'), Model(id='gpt-4o-realtime-preview', created=1727659998, object='model', owned_by='system'), Model(id='gpt-3.5-turbo-16k', created=1683758102, object='model', owned_by='openai-internal'), Model(id='gpt-4o', created=1715367049, object='model', owned_by='system'), Model(id='text-embedding-3-small', created=1705948997, object='model', owned_by='system'), Model(id='gpt-4-1106-preview', created=1698957206, object='model', owned_by='system'), Model(id='text-embedding-ada-002', created=1671217299, object='model', owned_by='openai-internal'), Model(id='gpt-4-0613', created=1686588896, object='model', owned_by='openai'), Model(id='o1-2024-12-17', created=1734326976, object='model', owned_by='system')], object='list')

In [ ]:
import json
import ntpath
import glob
import os
import numpy as np
from openai import OpenAI
import pandas as pd
import re

df = pd.read_csv('/content/ALG PADIC Diac POS.csv', sep=',')
df.head()

,ALG-DIACT-Sentences,Padic-ALG-POS,Padic-ALG,Padic-MSA
0,عَادُو الْنَاسْ يَتْبَاكَاوْ بَدِيتْ نَهْدَرْ ...,عادو_VERB الناس_NOUN يتباكاو_VERB بديت_VERB نه...,عادو الناس يتباكاو بديت نهدر من قلبي تقول نهدي...,تعالت أصوات الناس بالبكاء، بدأت أتحدث بانفعال ...
1,بَكِيتْ الْنَاسْ كَامَلْ سَكْتُو تَخْلَعْتْ فِ...,بكيت_VERB الناس_NOUN كامل_ADV سكتو_VERB تخلعت_...,بكيت الناس كامل سكتو تخلعت في روحي تقول كنت ننوم,فبكيت، سكت الناس جميعا و أنا ذهلت من نفسي ، كأ...
2,نَاضُو ﭬًاعْ سَلَمُو عَلْيَا وَ يَهْدَرُو مَعَ...,ناضو_VERB ﭭﺎع_ADV سلمو_VERB عليا_PRON و_CCONJ ...,ناضو ﭭﺎع سلمو عليا و يهدرو معايا نص بكا و نص ل...,قام الجميع يسلمون علي و يتحدثون معي ، نصفه بكا...
3,عَرْضُونَا لَلْعَشَا وَ كَانْ لَعَشَا يَكْفِي ...,عرضونا_VERB للعشا_NOUN و_CCONJ كان_VERB لعشا_N...,عرضونا للعشا و كان لعشا يكفي ليزاﻧڢيتي ﭭﺎع,دعينا للعشاء و كان العشاء يكفي جميع المدعوين
4,جَوَزْتْ اَيَامَاتْ رَوْعَ مَا نَنْسَاهَاشْ طُ...,جوزت_NOUN ايامات_NOUN روعة_ADJ ما_PART ننساهاش...,جوزت ايامات روعة ما ننساهاش طول حياتي,ﺃمضيت ﺃياما جميلة لن أنساها طوال عمري

In [ ]:
from tqdm import tqdm
client = OpenAI(
    # This is the default and can be omitted
    api_key='xxx',
)

translated = []

for i in tqdm(range(len(df))):
  prompt=     """
          Translate a given sentence from Algerian Dialect to Modern Standard Arabic.

                  Your input will include a sentence in Algerian Dialect along with the diacritization for each word and also the part of speech of each word.
                  Use this information to accurately translate the sentence into Modern Standard Arabic .
                  The translation should convey the original meaning while adhering to Modern Standard Arabic norms.

                  # Steps

                  1. **Understand Context**: Analyze the provided sentences, diacritization, and part of speech to grasp the overall context and structure.
                  2. **Word-by-Word Translation**: Consider each word and its diacritization and grammatical class to find an appropriate Modern Standard Arabic equivalent.
                  3. **Reconstruction**: Adjust the translated words to form a grammatically correct and coherent sentence in Modern Standard Arabic.
                  4. **Review for Meaning**: Ensure that the translated sentence accurately reflects the meaning and nuances of the original Algerian Dialect sentence.

                  # Output Format

                  - Provide a single translated sentence in Modern Standard Arabic.


                  *(Note: The example is shorter than typical to illustrate formatting. In practice, take into account longer sentences as well.)*
                  OUTPUT: JUST THE TRANSLATED SENTENCE IN Algerian Dialect  WITHOUT ANY ADDITIONAL TEXT.

                  """ + 'Sentence with diacritics' + df['ALG-DIACT-Sentences'][i] + '\n' + 'Sentece with part of speech' + df['Padic-ALG-POS'][i]

  response = client.chat.completions.create(
              model="gpt-4o-mini-2024-07-18",
              #response_format={"type":"json_object"},
              messages=[
                    {"role": "user", "content": prompt},
  ])

  translated.append(response.choices[0].message.content)
df['ALG-MSA-DIACT-POS-gpt-4o-mini-2024-07-18'] = translated
#gpt-4-1106-preview
#gpt-4o-mini-2024-07-18
#chatgpt-4o-latest

100%|██████████| 475/475 [05:17<00:00,  1.50it/s]

# **Claude Models**

In [ ]:
%%capture --no-stderr
!pip install --upgrade --quiet  langchain langchain-community langchainhub langchain-chroma bs4
!pip install -qU langchain-anthropic

In [ ]:
import json
import ntpath
import glob
import os
import numpy as np
import pandas as pd
import re

df = pd.read_csv('ALG-MSA-Diac-POS.csv', sep=',')

In [ ]:
df.head()

,ALG-DIACT-Sentences,Padic-ALG-POS,Padic-ALG,Padic-MSA,ALG-MSA-DIACT-POS-chatgpt-4o-latest,ALG-MSA-DIACT-POS-gpt-4-1106-preview,ALG-MSA-DIACT-POS-gpt-4o-mini-2024-07-18
0,عَادُو الْنَاسْ يَتْبَاكَاوْ بَدِيتْ نَهْدَرْ ...,عادو_VERB الناس_NOUN يتباكاو_VERB بديت_VERB نه...,عادو الناس يتباكاو بديت نهدر من قلبي تقول نهدي...,تعالت أصوات الناس بالبكاء، بدأت أتحدث بانفعال ...,عاد الناس يبكون، وبدأتُ أتحدث من قلبي، كأنني أ...,عاد الناس يشكون وبدأت أتكلم من قلبي كأني أهدي ...,عادَ الناسُ يَتَباكُونَ، بَدَأتُ أَتَكَلَّمُ م...
1,بَكِيتْ الْنَاسْ كَامَلْ سَكْتُو تَخْلَعْتْ فِ...,بكيت_VERB الناس_NOUN كامل_ADV سكتو_VERB تخلعت_...,بكيت الناس كامل سكتو تخلعت في روحي تقول كنت ننوم,فبكيت، سكت الناس جميعا و أنا ذهلت من نفسي ، كأ...,بكيت، فسكت جميع الناس، فشعرتُ بالخوف في داخلي،...,بكيتُ الناسُ جميعًا فصمتوا، فشعرتُ بالخوف في ن...,"ترجمة: ""بكيت الناس جميعًا، وسكتوا، شعرت بالخوف..."
2,نَاضُو ﭬًاعْ سَلَمُو عَلْيَا وَ يَهْدَرُو مَعَ...,ناضو_VERB ﭭﺎع_ADV سلمو_VERB عليا_PRON و_CCONJ ...,ناضو ﭭﺎع سلمو عليا و يهدرو معايا نص بكا و نص ل...,قام الجميع يسلمون علي و يتحدثون معي ، نصفه بكا...,نهضوا جميعًا وسلموا عليَّ وتحدثوا معي، نصفهم ك...,قاموا جميعًا بالسلام عليّ والحديث معي، نصفٌ يب...,نَاضُوا وِقَاعَ سَلَّمُوا عَلَيَّ وَ يَتَحَدَّ...
3,عَرْضُونَا لَلْعَشَا وَ كَانْ لَعَشَا يَكْفِي ...,عرضونا_VERB للعشا_NOUN و_CCONJ كان_VERB لعشا_N...,عرضونا للعشا و كان لعشا يكفي ليزاﻧڢيتي ﭭﺎع,دعينا للعشاء و كان العشاء يكفي جميع المدعوين,عرضونا للعشاء وكان العشاء يكفي للضيوف جميعًا.,دعونا للعشاء وكان العشاء كافيًا لجميع الحاضرين,عرضونا للعشاء وكان العشاء يكفي لوزننا.
4,جَوَزْتْ اَيَامَاتْ رَوْعَ مَا نَنْسَاهَاشْ طُ...,جوزت_NOUN ايامات_NOUN روعة_ADJ ما_PART ننساهاش...,جوزت ايامات روعة ما ننساهاش طول حياتي,ﺃمضيت ﺃياما جميلة لن أنساها طوال عمري,قضيتُ أيّامًا رائعةً لن أنساها طوالَ حياتي.,قضيت أيامًا رائعة لا أنساها طوال حياتي,جَوَّزْتُ أَيَّامًا رَائِعَةً مَا أَنْسَاهَا ط...

In [ ]:
import os
import getpass
from langchain_anthropic import ChatAnthropic
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
import json
import tqdm

os.environ["LANGCHAIN_TRACING_V2"] = "false"
os.environ["LANGCHAIN_API_KEY"] = "xxx"
os.environ["ANTHROPIC_API_KEY"] = "xxx"
model = ChatAnthropic(model= "claude-3-5-sonnet-20240620")#"claude-3-sonnet-20240229")

**With POS**

In [ ]:
translated = []

In [ ]:
from tqdm import tqdm

parser = StrOutputParser()

#system_template = "Translate the following into {language}:"

system_template =     """
         Translate a given sentence from Algerian Dialect to Modern Standard Arabic.

                  Your input will include a sentence in Algerian Dialect along with the diacritization for each word and also the part of speech of each word.
                  Use this information to accurately translate the sentence into Modern Standard Arabic .
                  The translation should convey the original meaning while adhering to Modern Standard Arabic norms.

                  # Steps

                  1. **Understand Context**: Analyze the provided sentences, diacritization, and part of speech to grasp the overall context and structure.
                  2. **Word-by-Word Translation**: Consider each word and its diacritization and grammatical class to find an appropriate Modern Standard Arabic equivalent.
                  3. **Reconstruction**: Adjust the translated words to form a grammatically correct and coherent sentence in Modern Standard Arabic.
                  4. **Review for Meaning**: Ensure that the translated sentence accurately reflects the meaning and nuances of the original Algerian Dialect sentence.

                  # Output Format

                  - Provide a single translated sentence in Modern Standard Arabic.

                  *(Note: The example is shorter than typical to illustrate formatting. In practice, take into account longer sentences as well.)*
                  OUTPUT: JUST THE TRANSLATED SENTENCE IN Algerian Dialect  WITHOUT ANY ADDITIONAL TEXT.
                  """

prompt_template = ChatPromptTemplate.from_messages(
    [("system", system_template), ("user", "{text}")]
)
chain = prompt_template | model | parser

i = 0
while  i<= len(df):
  translated.append(chain.invoke({"text":df['ALG-DIACT-Sentences'][i] + '\n' + 'Sentece with part of speech' + df['Padic-ALG-POS'][i]}))
  i+=1

KeyError: 475

# **Google Models**

In [ ]:
%%capture --no-stderr
!pip install --upgrade --quiet  langchain langchain-community langchainhub langchain-chroma bs4
!pip install -qU langchain-anthropic
!pip install -U langchain-google-genai

In [ ]:
import os
import getpass
from langchain_anthropic import ChatAnthropic
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
import json
import tqdm

#os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = 'xxxx'
#os.environ["ANTHROPIC_API_KEY"] = "xxxx"

In [ ]:
import json
import ntpath
import glob
import os
import numpy as np
import pandas as pd
import re

df = pd.read_csv('/content/ALG-MSA-Diac-POS.csv', sep=',')
df.head()

,ALG-DIACT-Sentences,Padic-ALG-POS,Padic-ALG,Padic-MSA,ALG-MSA-DIACT-POS-chatgpt-4o-latest,ALG-MSA-DIACT-POS-gpt-4-1106-preview,ALG-MSA-DIACT-POS-gpt-4o-mini-2024-07-18,ALG-MSA-DIACT-POS-claude-3-haiku-20240307,ALG-MSA-DIACT-POS-claude-3-sonnet-20240229,ALG-MSA-DIACT-POS-claude-3-opus-20240229,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20241022,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20240620
0,عَادُو الْنَاسْ يَتْبَاكَاوْ بَدِيتْ نَهْدَرْ ...,عادو_VERB الناس_NOUN يتباكاو_VERB بديت_VERB نه...,عادو الناس يتباكاو بديت نهدر من قلبي تقول نهدي...,تعالت أصوات الناس بالبكاء، بدأت أتحدث بانفعال ...,عاد الناس يبكون، وبدأتُ أتحدث من قلبي، كأنني أ...,عاد الناس يشكون وبدأت أتكلم من قلبي كأني أهدي ...,عادَ الناسُ يَتَباكُونَ، بَدَأتُ أَتَكَلَّمُ م...,عاد الناس يبكون، بدأت أتحدث من قلبي، تقول أهديهم,عادَ النَّاسُ يَتَنَازَعُونَ بَدَأْتُ أَتَحَدَ...,عاد الناس يبكون، بدأت أتحدث من قلبي كأنني أهدي...,عاد الناس يتباكون وبدأت أتحدث من قلبي كأنني أر...,عاد الناس يبكون وبدأت أتحدث من قلبي كأنني أهدي...
1,بَكِيتْ الْنَاسْ كَامَلْ سَكْتُو تَخْلَعْتْ فِ...,بكيت_VERB الناس_NOUN كامل_ADV سكتو_VERB تخلعت_...,بكيت الناس كامل سكتو تخلعت في روحي تقول كنت ننوم,فبكيت، سكت الناس جميعا و أنا ذهلت من نفسي ، كأ...,بكيت، فسكت جميع الناس، فشعرتُ بالخوف في داخلي،...,بكيتُ الناسُ جميعًا فصمتوا، فشعرتُ بالخوف في ن...,"ترجمة: ""بكيت الناس جميعًا، وسكتوا، شعرت بالخوف...",البشر بكوا كلهم وتكلمت داخلي قائلة كنت أنام,لَقَدْ بَكَتِ النَّاسُ كُلُّهُمْ، وَسَكَتُوا، ...,بكيت والناس جميعًا صمتوا، ارتعبت في نفسي كأنني...,بقي الناس جميعهم صامتين فخفت من نفسي كأنني كنت...,عندما بكيت، صمت الجميع، فارتعبت كأنني كنت نائماً.
2,نَاضُو ﭬًاعْ سَلَمُو عَلْيَا وَ يَهْدَرُو مَعَ...,ناضو_VERB ﭭﺎع_ADV سلمو_VERB عليا_PRON و_CCONJ ...,ناضو ﭭﺎع سلمو عليا و يهدرو معايا نص بكا و نص ل...,قام الجميع يسلمون علي و يتحدثون معي ، نصفه بكا...,نهضوا جميعًا وسلموا عليَّ وتحدثوا معي، نصفهم ك...,قاموا جميعًا بالسلام عليّ والحديث معي، نصفٌ يب...,نَاضُوا وِقَاعَ سَلَّمُوا عَلَيَّ وَ يَتَحَدَّ...,استقبلوا عليّ وتحدثوا معي، بعضهم فهم وبعضهم لا.,يُصَافِحُونِي ثُمَّ يُحَادِثُونَنِي بَعْضَ الْ...,استيقظوا جميعا وسلموا علي وتحدثوا معي نصفهم با...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي نصف الكلا...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي، نصف كلام...
3,عَرْضُونَا لَلْعَشَا وَ كَانْ لَعَشَا يَكْفِي ...,عرضونا_VERB للعشا_NOUN و_CCONJ كان_VERB لعشا_N...,عرضونا للعشا و كان لعشا يكفي ليزاﻧڢيتي ﭭﺎع,دعينا للعشاء و كان العشاء يكفي جميع المدعوين,عرضونا للعشاء وكان العشاء يكفي للضيوف جميعًا.,دعونا للعشاء وكان العشاء كافيًا لجميع الحاضرين,عرضونا للعشاء وكان العشاء يكفي لوزننا.,أحضروا لنا العشاء وكان العشاء كافيًا للجميع,أَكَرَمُونَا بِالْعَشَاءِ وَكَانَ الْعَشَاءُ ك...,دعونا للعشاء وكان العشاء يكفي لجيش كامل,دعونا للعشاء وكان العشاء يكفي الضيوف جميعاً,دعونا إلى العشاء وكان الطعام يكفي الجميع.
4,جَوَزْتْ اَيَامَاتْ رَوْعَ مَا نَنْسَاهَاشْ طُ...,جوزت_NOUN ايامات_NOUN روعة_ADJ ما_PART ننساهاش...,جوزت ايامات روعة ما ننساهاش طول حياتي,ﺃمضيت ﺃياما جميلة لن أنساها طوال عمري,قضيتُ أيّامًا رائعةً لن أنساها طوالَ حياتي.,قضيت أيامًا رائعة لا أنساها طوال حياتي,جَوَّزْتُ أَيَّامًا رَائِعَةً مَا أَنْسَاهَا ط...,لن أنسى تلك الأيام الرائعة طوال حياتي,قَضَيْتُ أَيَّامًا رَائِعَةً لَنْ أَنْسَاهَا ط...,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي

In [ ]:
import getpass
import os

os.environ["GOOGLE_API_KEY"] = getpass.getpass("xxx")

AIzaSyBadWzNJI-NRPOEia-EvF9kZJDNauhDi6g··········

In [ ]:
import os
import getpass
from langchain_anthropic import ChatAnthropic
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
import json
import tqdm
from tqdm import tqdm

from langchain_google_genai import ChatGoogleGenerativeAI

# If there is no env variable set for API key, you can pass the API key
# to the parameter `google_api_key` of the `ChatGoogleGenerativeAI` function:
# `google_api_key="key"`.

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    google_api_key='xxx'
    # other params...
)
#gemini-1.5-flash
#gemini-1.5-flash-8b
#gemini-1.5-pro

In [ ]:
translated = []
system_template =    """
 Translate a given sentence from Algerian Dialect to Modern Standard Arabic.

                  Your input will include a sentence in Algerian Dialect along with the diacritization for each word and also the part of speech of each word.
                  Use this information to accurately translate the sentence into Modern Standard Arabic .
                  The translation should convey the original meaning while adhering to Modern Standard Arabic norms.

                  # Steps

                  1. **Understand Context**: Analyze the provided sentences, diacritization, and part of speech to grasp the overall context and structure.
                  2. **Word-by-Word Translation**: Consider each word and its diacritization and grammatical class to find an appropriate Modern Standard Arabic equivalent.
                  3. **Reconstruction**: Adjust the translated words to form a grammatically correct and coherent sentence in Modern Standard Arabic.
                  4. **Review for Meaning**: Ensure that the translated sentence accurately reflects the meaning and nuances of the original Algerian Dialect sentence.

                  # Output Format

                  - Provide a single translated sentence in Modern Standard Arabic.


                  *(Note: The example is shorter than typical to illustrate formatting. In practice, take into account longer sentences as well.)*
                  OUTPUT: JUST THE TRANSLATED SENTENCE IN Algerian Dialect  WITHOUT ANY ADDITIONAL TEXT.
                  """

for i in tqdm(range(len(df))):
  messages = [
    (
        "system",
        system_template,
    ),
    ("human", '\n Sentence with diacritics: \n' + df['ALG-DIACT-Sentences'][i] + '\n' + 'Sentece with part of speech: \n' + df['Padic-ALG-POS'][i]),
  ]
  ai_msg = llm.invoke(messages)
  translated.append(ai_msg.content)


df['ALG-MSA-DIACT-POS-gemini-1.5-flash'] = translated
df.to_csv('ALG-MSA-Diac-POS.csv', index=False)
print('completed successfully')

100%|██████████| 475/475 [02:37<00:00,  3.02it/s]

completed successfully

In [ ]:
translated = []
system_template =    """
                                    Translate a given sentence from Modern Standard Arabic to Algerian Dialect.

                  Your input will include a sentence in Modern Standard Arabic. Use this information to accurately translate the sentence into Algerian Dialect. The translation should convey the original meaning while adhering to Algerian Dialect norms.

                  # Steps

                  1. **Understand Context**: Analyze the provided sentence to grasp the overall context and structure.
                  2. **Word-by-Word Translation**: Consider each word to find an appropriate Algerian Dialect equivalent.
                  3. **Reconstruction**: Adjust the translated words to form a grammatically correct and coherent sentence in Algerian Dialect.
                  4. **Review for Meaning**: Ensure that the translated sentence accurately reflects the meaning and nuances of the original Modern Standard Arabic sentence.

                  # Output Format

                  - Provide a single translated sentence in Algerian Dialect.

                  *(Note: The example is shorter than typical to illustrate formatting. In practice, take into account longer sentences as well.)*
                  OUTPUT: JUST THE TRANSLATED SENTENCE IN Algerian Dialect  WITHOUT ANY ADDITIONAL TEXT.

                  """

for i in tqdm(range(len(df))):
  messages = [
    (
        "system",
        system_template,
    ),
    ("human", df['Sentence_MSA'][i]),
  ]
  ai_msg = llm.invoke(messages)
  translated.append(ai_msg.content)

df['MSA-gemini-1.5-flash-8b'] = translated
df.to_csv('MSA-POS-Sentences-OpenAi-Models.csv', index=False)
print('completed successfully')

100%|██████████| 475/475 [02:44<00:00,  2.89it/s]

completed successfully