In [ ]:
%%capture
!pip install sacrebleu
!pip install git+https://github.com/google-research/bleurt.git

# **Comet metric**

In [ ]:
!pip install --upgrade pip  # ensures that pip is current
!pip install unbabel-comet

Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (24.1.2)
Collecting pip
  Downloading pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-25.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 15.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-25.0.1
Collecting unbabel-comet
  Downloading unbabel_comet-2.2.5-py3-none-any.whl.metadata (19 kB)
Collecting entmax<2.0,>=1.1 (from unbabel-comet)
  Downloading entmax-1.3-py3-none-any.whl.metadata (348 bytes)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (0.29.3)
Collecting jsonargparse==3.13.1 (from unbabel-comet)
  Downloading jsonargparse-3.13.1-py3-none-any.whl.metadata (55 kB)
Collecting numpy<2.0.0,>=1.20.0 (from unbabel-comet)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: pandas>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (2.2.2)
Collecting protobuf<5.0.0,>=4.24.4 (from unbabel-comet)
  Downloading protobuf-4.25.6-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pytorch-lightning<3.0.0,>=2.0.0 (from unbabel-comet)
  Downloading pytorch_lightning-2.5.1-py3-none-any.whl.metadata (20 kB)
Collecting sacrebleu<3.0.0,>=2.0.0 (from unbabel-comet)
  Downloading sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
Requirement already satisfied: scipy<2.0.0,>=1.5.4 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (1.14.1)
Requirement already satisfied: sentencepiece<0.3.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (0.2.0)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (2.6.0+cu124)
Collecting torchmetrics<0.11.0,>=0.10.2 (from unbabel-comet)
  Downloading torchmetrics-0.10.3-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: transformers<5.0,>=4.17 in /usr/local/lib/python3.11/dist-packages (from unbabel-comet) (4.50.0)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.11/dist-packages (from jsonargparse==3.13.1->unbabel-comet) (6.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.1->unbabel-comet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.1->unbabel-comet) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4.1->unbabel-comet) (2025.1)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Downloading lightning_utilities-0.14.2-py3-none-any.whl.metadata (5.6 kB)
Collecting portalocker (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Downloading portalocker-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.11/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet) (0.9.0)
Collecting colorama (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet) (5.3.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.6.0->unbabel-comet)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->unbabel-comet) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.6.0->unbabel-comet) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0,>=4.17->unbabel-comet) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0,>=4.17->unbabel-comet) (0.5.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (3.11.14)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from lightning-utilities>=0.10.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (75.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.1->unbabel-comet) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.6.0->unbabel-comet) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2025.1.31)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (1.18.3)
Downloading unbabel_comet-2.2.5-py3-none-any.whl (96 kB)
Downloading jsonargparse-3.13.1-py3-none-any.whl (101 kB)
Downloading entmax-1.3-py3-none-any.whl (13 kB)
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 32.1 MB/s eta 0:00:00
Downloading protobuf-4.25.6-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Downloading pytorch_lightning-2.5.1-py3-none-any.whl (822 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.0/823.0 kB 20.1 MB/s eta 0:00:00
Downloading sacrebleu-2.5.1-py3-none-any.whl (104 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 40.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 74.8 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 33.1 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 27.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 41.5 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 65.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 54.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 57.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 65.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 107.5 MB/s eta 0:00:00
Downloading torchmetrics-0.10.3-py3-none-any.whl (529 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 22.9 MB/s eta 0:00:00
Downloading lightning_utilities-0.14.2-py3-none-any.whl (28 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.1.1-py3-none-any.whl (19 kB)
Installing collected packages: protobuf, portalocker, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, lightning-utilities, jsonargparse, colorama, sacrebleu, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torchmetrics, entmax, pytorch-lightning, unbabel-comet
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.4
    Uninstalling protobuf-5.29.4:
      Successfully uninstalled protobuf-5.29.4
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.71.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.6 which is incompatible.
Successfully installed colorama-0.4.6 entmax-1.3 jsonargparse-3.13.1 lightning-utilities-0.14.2 numpy-1.26.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 portalocker-3.1.1 protobuf-4.25.6 pytorch-lightning-2.5.1 sacrebleu-2.5.1 torchmetrics-0.10.3 unbabel-comet-2.2.5

In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))
    !nvidia-smi

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4
Thu Mar 27 12:50:56 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             11W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [ ]:
from comet import download_model, load_from_checkpoint

model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

model.ckpt:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

hparams.yaml:   0%|          | 0.00/567 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.40k [00:00<?, ?B/s]

LICENSE:   0%|          | 0.00/9.69k [00:00<?, ?B/s]

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.5.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

In [ ]:
import pandas as pd

df = pd.read_csv('/content/ALG-MSA-Diac-POS.csv', sep=',')
df.head()

,ALG-DIACT-Sentences,Padic-ALG-POS,Padic-ALG,Padic-MSA,ALG-MSA-DIACT-POS-chatgpt-4o-latest,ALG-MSA-DIACT-POS-gpt-4-1106-preview,ALG-MSA-DIACT-POS-gpt-4o-mini-2024-07-18,ALG-MSA-DIACT-POS-claude-3-haiku-20240307,ALG-MSA-DIACT-POS-claude-3-sonnet-20240229,ALG-MSA-DIACT-POS-claude-3-opus-20240229,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20241022,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20240620,ALG-MSA-DIACT-POS-gemini-1.5-flash-8b,ALG-MSA-DIACT-POS-gemini-1.5-pro,ALG-MSA-DIACT-POS-gemini-1.5-flash,ALG-MSA-DIACT-llama3.1:8b-instruct-q5_0,ALG-MSA-DIACT-gemma2:9b-instruct-q5_0
0,عَادُو الْنَاسْ يَتْبَاكَاوْ بَدِيتْ نَهْدَرْ ...,عادو_VERB الناس_NOUN يتباكاو_VERB بديت_VERB نه...,عادو الناس يتباكاو بديت نهدر من قلبي تقول نهدي...,تعالت أصوات الناس بالبكاء، بدأت أتحدث بانفعال ...,عاد الناس يبكون، وبدأتُ أتحدث من قلبي، كأنني أ...,عاد الناس يشكون وبدأت أتكلم من قلبي كأني أهدي ...,عادَ الناسُ يَتَباكُونَ، بَدَأتُ أَتَكَلَّمُ م...,عاد الناس يبكون، بدأت أتحدث من قلبي، تقول أهديهم,عادَ النَّاسُ يَتَنَازَعُونَ بَدَأْتُ أَتَحَدَ...,عاد الناس يبكون، بدأت أتحدث من قلبي كأنني أهدي...,عاد الناس يتباكون وبدأت أتحدث من قلبي كأنني أر...,عاد الناس يبكون وبدأت أتحدث من قلبي كأنني أهدي...,رجع الناس يبكون بدأت أُحزن من قلبي تقولُ نهدي ...,عندما يتباكى الناسُ، بدأتُ أتكلم من قلبي، كأنّ...,عاد الناس يبكون، فبدأت أتحدث من قلبي، أقول أهد...,أعدوا الناس يبكيين على ما بديتهم من قلوبهم.,ان عادوا الناس يتباكون بدأت نهدر من قلبي تقو...
1,بَكِيتْ الْنَاسْ كَامَلْ سَكْتُو تَخْلَعْتْ فِ...,بكيت_VERB الناس_NOUN كامل_ADV سكتو_VERB تخلعت_...,بكيت الناس كامل سكتو تخلعت في روحي تقول كنت ننوم,فبكيت، سكت الناس جميعا و أنا ذهلت من نفسي ، كأ...,بكيت، فسكت جميع الناس، فشعرتُ بالخوف في داخلي،...,بكيتُ الناسُ جميعًا فصمتوا، فشعرتُ بالخوف في ن...,"ترجمة: ""بكيت الناس جميعًا، وسكتوا، شعرت بالخوف...",البشر بكوا كلهم وتكلمت داخلي قائلة كنت أنام,لَقَدْ بَكَتِ النَّاسُ كُلُّهُمْ، وَسَكَتُوا، ...,بكيت والناس جميعًا صمتوا، ارتعبت في نفسي كأنني...,بقي الناس جميعهم صامتين فخفت من نفسي كأنني كنت...,عندما بكيت، صمت الجميع، فارتعبت كأنني كنت نائماً.,بكيت الناس جميعًا، وسكتوا، وتخلّعتُ في روحي، ق...,بَكى الناسُ جميعاً فسَكَتوا فَخِفتُ في نفسي وق...,بكى الناس جميعاً، فصمتوا، وارتعبت روحي، قائلة:...,أنا أتمنى أن يكون الجميع قد ناموا بسلام في قلوبي.,بكت الناس كاملا سكّت وأخذتْ فِي روحها تُقول كا...
2,نَاضُو ﭬًاعْ سَلَمُو عَلْيَا وَ يَهْدَرُو مَعَ...,ناضو_VERB ﭭﺎع_ADV سلمو_VERB عليا_PRON و_CCONJ ...,ناضو ﭭﺎع سلمو عليا و يهدرو معايا نص بكا و نص ل...,قام الجميع يسلمون علي و يتحدثون معي ، نصفه بكا...,نهضوا جميعًا وسلموا عليَّ وتحدثوا معي، نصفهم ك...,قاموا جميعًا بالسلام عليّ والحديث معي، نصفٌ يب...,نَاضُوا وِقَاعَ سَلَّمُوا عَلَيَّ وَ يَتَحَدَّ...,استقبلوا عليّ وتحدثوا معي، بعضهم فهم وبعضهم لا.,يُصَافِحُونِي ثُمَّ يُحَادِثُونَنِي بَعْضَ الْ...,استيقظوا جميعا وسلموا علي وتحدثوا معي نصفهم با...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي نصف الكلا...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي، نصف كلام...,لقد ساعدوني وسلموا عليّ و يتحدثون معي نصيب من ...,قاموا فجأة وسلموا عليّ وتحدثوا معي نصفه بالبكا...,قاموا جميعا وسلموا عليّ، ويتحدثون معي نصف بكاء...,أنا أتعلم أن السلّام على إحدى الأولياء وهو يدخ...,لقد أخبروني سلامًا وعادوا معي نص بَكَةٍ و نص ...
3,عَرْضُونَا لَلْعَشَا وَ كَانْ لَعَشَا يَكْفِي ...,عرضونا_VERB للعشا_NOUN و_CCONJ كان_VERB لعشا_N...,عرضونا للعشا و كان لعشا يكفي ليزاﻧڢيتي ﭭﺎع,دعينا للعشاء و كان العشاء يكفي جميع المدعوين,عرضونا للعشاء وكان العشاء يكفي للضيوف جميعًا.,دعونا للعشاء وكان العشاء كافيًا لجميع الحاضرين,عرضونا للعشاء وكان العشاء يكفي لوزننا.,أحضروا لنا العشاء وكان العشاء كافيًا للجميع,أَكَرَمُونَا بِالْعَشَاءِ وَكَانَ الْعَشَاءُ ك...,دعونا للعشاء وكان العشاء يكفي لجيش كامل,دعونا للعشاء وكان العشاء يكفي الضيوف جميعاً,دعونا إلى العشاء وكان الطعام يكفي الجميع.,عرضونا للعشاء وكان العشاء يكفي لِإِزْدِرَارِيتِي,عَرَضُوا علينا العشاء، وكان العشاء كافياً.,عرضونا للعشاء وكان عشاء يكفي ليزانيتينا,أردونا للعشاء، والله كنا العشاء يكفي ليزاني.,قدموا لنا العشاء وكان العشاء يكفي لي. \n
4,جَوَزْتْ اَيَامَاتْ رَوْعَ مَا نَنْسَاهَاشْ طُ...,جوزت_NOUN ايامات_NOUN روعة_ADJ ما_PART ننساهاش...,جوزت ايامات روعة ما ننساهاش طول حياتي,ﺃمضيت ﺃياما جميلة لن أنساها طوال عمري,قضيتُ أيّامًا رائعةً لن أنساها طوالَ حياتي.,قضيت أيامًا رائعة لا أنساها طوال حياتي,جَوَّزْتُ أَيَّامًا رَائِعَةً مَا أَنْسَاهَا ط...,لن أنسى تلك الأيام الرائعة طوال حياتي,قَضَيْتُ أَيَّامًا رَائِعَةً لَنْ أَنْسَاهَا ط...,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي,عشتُ أيّامًا رائعة لن أنساها طوال حياتي,قضيتُ أيامًا رائعةً لن أنساها طوال حياتي.,عشت أياماً رائعة لا أنساها طوال حياتي,أنا جازت أيامًا روعة ما تنسى طوال حياتي.,لقد قضيت أياماً روعةً لم أنساها طوال حياتي. \n

With POS

In [ ]:
%%capture
count = 0
import pandas as pd

for i in range(len(df)):

  data = [
      {
          "src": df['ALG-DIACT-Sentences'][i],
          "mt": df['ALG-MSA-DIACT-gemma2:9b-instruct-q5_0'][i],
          "ref": df['Padic-MSA'][i]
      }
  ]
  model_output = model.predict(data, gpus=0)
  count+= model_output['scores'][0]

INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs

In [ ]:
print('final score with POS is:', count/len(df))

final score with POS is: 0.48111841722538595

# **CamelBERT similarity**

In [ ]:
import torch
from transformers import AutoModel, AutoTokenizer
from sklearn.metrics.pairwise import cosine_similarity

def get_sentence_embedding(sentence, model, tokenizer):
    # Tokenize the input sentence
    inputs = tokenizer(sentence, return_tensors='pt', padding=True, truncation=True)

    # Get the hidden states from the model
    with torch.no_grad():
        outputs = model(**inputs)

    # Get the embeddings from the last hidden state
    # We take the mean of all token embeddings to get the sentence embedding
    embeddings = outputs.last_hidden_state.mean(dim=1)

    return embeddings

def calculate_cosine_similarity(embedding1, embedding2):
    # Calculate cosine similarity
    similarity = cosine_similarity(embedding1.numpy(), embedding2.numpy())
    return similarity[0][0]

In [ ]:
# Load pre-trained model and tokenizer
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa"  # You can use any pre-trained transformer model here
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/468 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/305k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

In [ ]:
import pandas as pd

df = pd.read_csv('/content/ALG-MSA-Diac-POS.csv', sep=',')
df.head()

,ALG-DIACT-Sentences,Padic-ALG-POS,Padic-ALG,Padic-MSA,ALG-MSA-DIACT-POS-chatgpt-4o-latest,ALG-MSA-DIACT-POS-gpt-4-1106-preview,ALG-MSA-DIACT-POS-gpt-4o-mini-2024-07-18,ALG-MSA-DIACT-POS-claude-3-haiku-20240307,ALG-MSA-DIACT-POS-claude-3-sonnet-20240229,ALG-MSA-DIACT-POS-claude-3-opus-20240229,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20241022,ALG-MSA-DIACT-POS-Claude-3-5-sonnet-20240620,ALG-MSA-DIACT-POS-gemini-1.5-flash-8b,ALG-MSA-DIACT-POS-gemini-1.5-pro,ALG-MSA-DIACT-POS-gemini-1.5-flash,ALG-MSA-DIACT-llama3.1:8b-instruct-q5_0,ALG-MSA-DIACT-gemma2:9b-instruct-q5_0
0,عَادُو الْنَاسْ يَتْبَاكَاوْ بَدِيتْ نَهْدَرْ ...,عادو_VERB الناس_NOUN يتباكاو_VERB بديت_VERB نه...,عادو الناس يتباكاو بديت نهدر من قلبي تقول نهدي...,تعالت أصوات الناس بالبكاء، بدأت أتحدث بانفعال ...,عاد الناس يبكون، وبدأتُ أتحدث من قلبي، كأنني أ...,عاد الناس يشكون وبدأت أتكلم من قلبي كأني أهدي ...,عادَ الناسُ يَتَباكُونَ، بَدَأتُ أَتَكَلَّمُ م...,عاد الناس يبكون، بدأت أتحدث من قلبي، تقول أهديهم,عادَ النَّاسُ يَتَنَازَعُونَ بَدَأْتُ أَتَحَدَ...,عاد الناس يبكون، بدأت أتحدث من قلبي كأنني أهدي...,عاد الناس يتباكون وبدأت أتحدث من قلبي كأنني أر...,عاد الناس يبكون وبدأت أتحدث من قلبي كأنني أهدي...,رجع الناس يبكون بدأت أُحزن من قلبي تقولُ نهدي ...,عندما يتباكى الناسُ، بدأتُ أتكلم من قلبي، كأنّ...,عاد الناس يبكون، فبدأت أتحدث من قلبي، أقول أهد...,أعدوا الناس يبكيين على ما بديتهم من قلوبهم.,ان عادوا الناس يتباكون بدأت نهدر من قلبي تقو...
1,بَكِيتْ الْنَاسْ كَامَلْ سَكْتُو تَخْلَعْتْ فِ...,بكيت_VERB الناس_NOUN كامل_ADV سكتو_VERB تخلعت_...,بكيت الناس كامل سكتو تخلعت في روحي تقول كنت ننوم,فبكيت، سكت الناس جميعا و أنا ذهلت من نفسي ، كأ...,بكيت، فسكت جميع الناس، فشعرتُ بالخوف في داخلي،...,بكيتُ الناسُ جميعًا فصمتوا، فشعرتُ بالخوف في ن...,"ترجمة: ""بكيت الناس جميعًا، وسكتوا، شعرت بالخوف...",البشر بكوا كلهم وتكلمت داخلي قائلة كنت أنام,لَقَدْ بَكَتِ النَّاسُ كُلُّهُمْ، وَسَكَتُوا، ...,بكيت والناس جميعًا صمتوا، ارتعبت في نفسي كأنني...,بقي الناس جميعهم صامتين فخفت من نفسي كأنني كنت...,عندما بكيت، صمت الجميع، فارتعبت كأنني كنت نائماً.,بكيت الناس جميعًا، وسكتوا، وتخلّعتُ في روحي، ق...,بَكى الناسُ جميعاً فسَكَتوا فَخِفتُ في نفسي وق...,بكى الناس جميعاً، فصمتوا، وارتعبت روحي، قائلة:...,أنا أتمنى أن يكون الجميع قد ناموا بسلام في قلوبي.,بكت الناس كاملا سكّت وأخذتْ فِي روحها تُقول كا...
2,نَاضُو ﭬًاعْ سَلَمُو عَلْيَا وَ يَهْدَرُو مَعَ...,ناضو_VERB ﭭﺎع_ADV سلمو_VERB عليا_PRON و_CCONJ ...,ناضو ﭭﺎع سلمو عليا و يهدرو معايا نص بكا و نص ل...,قام الجميع يسلمون علي و يتحدثون معي ، نصفه بكا...,نهضوا جميعًا وسلموا عليَّ وتحدثوا معي، نصفهم ك...,قاموا جميعًا بالسلام عليّ والحديث معي، نصفٌ يب...,نَاضُوا وِقَاعَ سَلَّمُوا عَلَيَّ وَ يَتَحَدَّ...,استقبلوا عليّ وتحدثوا معي، بعضهم فهم وبعضهم لا.,يُصَافِحُونِي ثُمَّ يُحَادِثُونَنِي بَعْضَ الْ...,استيقظوا جميعا وسلموا علي وتحدثوا معي نصفهم با...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي نصف الكلا...,نهضوا جميعاً وسلموا عليّ وتحدثوا معي، نصف كلام...,لقد ساعدوني وسلموا عليّ و يتحدثون معي نصيب من ...,قاموا فجأة وسلموا عليّ وتحدثوا معي نصفه بالبكا...,قاموا جميعا وسلموا عليّ، ويتحدثون معي نصف بكاء...,أنا أتعلم أن السلّام على إحدى الأولياء وهو يدخ...,لقد أخبروني سلامًا وعادوا معي نص بَكَةٍ و نص ...
3,عَرْضُونَا لَلْعَشَا وَ كَانْ لَعَشَا يَكْفِي ...,عرضونا_VERB للعشا_NOUN و_CCONJ كان_VERB لعشا_N...,عرضونا للعشا و كان لعشا يكفي ليزاﻧڢيتي ﭭﺎع,دعينا للعشاء و كان العشاء يكفي جميع المدعوين,عرضونا للعشاء وكان العشاء يكفي للضيوف جميعًا.,دعونا للعشاء وكان العشاء كافيًا لجميع الحاضرين,عرضونا للعشاء وكان العشاء يكفي لوزننا.,أحضروا لنا العشاء وكان العشاء كافيًا للجميع,أَكَرَمُونَا بِالْعَشَاءِ وَكَانَ الْعَشَاءُ ك...,دعونا للعشاء وكان العشاء يكفي لجيش كامل,دعونا للعشاء وكان العشاء يكفي الضيوف جميعاً,دعونا إلى العشاء وكان الطعام يكفي الجميع.,عرضونا للعشاء وكان العشاء يكفي لِإِزْدِرَارِيتِي,عَرَضُوا علينا العشاء، وكان العشاء كافياً.,عرضونا للعشاء وكان عشاء يكفي ليزانيتينا,أردونا للعشاء، والله كنا العشاء يكفي ليزاني.,قدموا لنا العشاء وكان العشاء يكفي لي. \n
4,جَوَزْتْ اَيَامَاتْ رَوْعَ مَا نَنْسَاهَاشْ طُ...,جوزت_NOUN ايامات_NOUN روعة_ADJ ما_PART ننساهاش...,جوزت ايامات روعة ما ننساهاش طول حياتي,ﺃمضيت ﺃياما جميلة لن أنساها طوال عمري,قضيتُ أيّامًا رائعةً لن أنساها طوالَ حياتي.,قضيت أيامًا رائعة لا أنساها طوال حياتي,جَوَّزْتُ أَيَّامًا رَائِعَةً مَا أَنْسَاهَا ط...,لن أنسى تلك الأيام الرائعة طوال حياتي,قَضَيْتُ أَيَّامًا رَائِعَةً لَنْ أَنْسَاهَا ط...,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي,قضيت أياماً رائعة لن أنساها طوال حياتي,عشتُ أيّامًا رائعة لن أنساها طوال حياتي,قضيتُ أيامًا رائعةً لن أنساها طوال حياتي.,عشت أياماً رائعة لا أنساها طوال حياتي,أنا جازت أيامًا روعة ما تنسى طوال حياتي.,لقد قضيت أياماً روعةً لم أنساها طوال حياتي. \n

With POS insertion

In [ ]:
similarity = 0
df.fillna('/', inplace=True)
for i in range(len(df)):
  # Calculate cosine similarity
  similarity += calculate_cosine_similarity(get_sentence_embedding(df['ALG-MSA-DIACT-gemma2:9b-instruct-q5_0'][i], model, tokenizer), get_sentence_embedding(df['Padic-MSA'][i], model, tokenizer))

print(f"Cosine Similarity: {similarity/len(df)}")

Cosine Similarity: 0.5118720352649688

# **Bleu and Chrf++**

In [ ]:
%%capture
!pip install sacrebleu
import sacrebleu

In [ ]:
# Calculate chrf score
chrf  = sacrebleu.corpus_chrf(list(df['Padic-MSA']), [list(df['ALG-MSA-DIACT-gemma2:9b-instruct-q5_0'])])

# Print chrf score
print(f"chrf  score: {chrf.score:.2f}")


# Calculate BLEU score
bleu  = sacrebleu.corpus_bleu(list(df['Padic-MSA']), [list(df['ALG-MSA-DIACT-gemma2:9b-instruct-q5_0'])])

# Print BLEU score
print(f"bleu  score: {bleu.score:.2f}")

chrf  score: 8.26
bleu  score: 0.33